Updated activate script to check for already activated environments

diff --git a/Bonsai.LinuxEnvironmentTemplate/activate b/Bonsai.LinuxEnvironmentTemplate/activate
--- a/Bonsai.LinuxEnvironmentTemplate/activate
+++ b/Bonsai.LinuxEnvironmentTemplate/activate
@@ -1,5 +1,9 @@
 #!/bin/bash
 # activate.sh
+if [[ -z "${BONSAI_EXE_PATH}" ]]; then
+    echo "Error! Cannot have multiple bonsai environments activated at the same time. Please deactivate the previous environment before activating the new one."
+    exit 125
+fi
 BONSAI_ENV_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
 export BONSAI_EXE_PATH="$BONSAI_ENV_DIR/Bonsai.exe"
 export ORIGINAL_PS1="$PS1"
